/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/your-org/x509-crystal */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "shim.go"

#include <stdlib.h>
#include <stdint.h>

typedef struct {
	char *ca_cert;
	char *ca_key;
	char *client_cert;
	char *client_key;
	char *error;
	int   status; // 0 = success, 1 = error
} X509Result;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


//
// Generates a CA certificate and a client certificate signed by that CA.
//
// Parameters:
//   cn              - common name applied to both certificates
//   days            - validity period in days; in CA-signed mode applies only
//                     to the client cert (the provided CA's validity is fixed)
//   ca_algo         - CA key algorithm:     0 = ECDSA P-256, 1 = RSA
//   client_algo     - client key algorithm: 0 = ECDSA P-256, 1 = RSA
//   ca_rsa_bits     - RSA bit size for CA key     (ignored when ca_algo = 0)
//   client_rsa_bits - RSA bit size for client key (ignored when client_algo = 0)
//   provided_ca_cert - PEM of an existing CA certificate, or NULL for self-signed
//   provided_ca_key  - PEM of the matching CA private key, or NULL for self-signed
//
// Returns a heap-allocated X509Result. Caller MUST call x509_free() when done.
// On error, status = 1 and the error field contains a message; all cert fields are NULL.
// On success, status = 0 and all four cert/key fields are populated.
extern X509Result* x509_generate(char* cn, int days, int ca_algo, int client_algo, int ca_rsa_bits, int client_rsa_bits, char* provided_ca_cert, char* provided_ca_key);

//
// Releases all memory allocated by x509_generate.
// Must be called exactly once per result returned by x509_generate.
// Safe to call with a NULL pointer.
extern void x509_free(X509Result* result);

#ifdef __cplusplus
}
#endif
